Repository Pathum-lakshan/Spring-Boot-With-Spring-Security, pull requests merged in 2023-10, with the labels that each got.

#36 fist test collaborate push
  README.md
Labels: feature

#38 Feature/in memory cache implement #33
  pom.xml
  src/main/java/com/security/jwt0Auth/Application.java
  src/main/java/com/security/jwt0Auth/component/security/JwtAuthenticationFilter.java
  src/main/java/com/security/jwt0Auth/config/Configuration.java
  src/main/java/com/security/jwt0Auth/config/cache/CachingConfiguration.java
  src/main/java/com/security/jwt0Auth/config/email/EmailConfig.java
  src/main/java/com/security/jwt0Auth/config/security/SecurityConfiguration.java
  src/main/java/com/security/jwt0Auth/service/admin/impl/AuthenticationServiceImpl.java
  src/main/java/com/security/jwt0Auth/service/admin/impl/UserServiceImpl.java
  src/main/java/com/security/jwt0Auth/service/setup/cache/CacheManagerService.java
  src/main/java/com/security/jwt0Auth/service/setup/cache/impl/CacheManagerServiceImpl.java
  src/main/java/com/security/jwt0Auth/service/setup/security/JwtService.java
  src/main/java/com/security/jwt0Auth/service/setup/security/impl/JwtServiceImpl.java
  src/main/java/com/security/jwt0Auth/service/test/impl/TestServiceImpl.java
  src/main/java/com/security/jwt0Auth/util/contant/Constant.java
  src/main/resources/application.properties
  src/main/resources/database/dbStructure/sqlScript.sql
  src/main/resources/database/springSecurity-2023_10_01_23_08_20-dump.sql
Labels: feature

#40 refactor db resource
  src/main/resources/database/diagram/springSecurity.mwb
  src/main/resources/database/diagram/springSecurity.mwb.bak
  src/main/resources/database/dump/springSecurity-2023_10_01_23_08_20-dump.sql
Labels: documentation

#43 Invalid/test co author #42
  README.md
Labels: invalid

#44 Update FUNDING.yml
  .github/FUNDING.yml
Labels: wontfix

#45 feature/implement-swagger-documentation-#39
  pom.xml
  src/main/java/com/security/jwt0Auth/Application.java
  src/main/java/com/security/jwt0Auth/config/Configuration.java
  src/main/java/com/security/jwt0Auth/config/doc/OpenAPIConfig.java
  src/main/java/com/security/jwt0Auth/config/security/SecurityConfiguration.java
Labels: feature

#47 FUNDING.yml changed
  .github/FUNDING.yml
Labels: help wanted

#48 Update issue templates
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#50 Enhancement/improve email #49
  src/main/java/com/security/jwt0Auth/service/setup/email/EmailService.java
  src/main/java/com/security/jwt0Auth/service/setup/email/impl/EmailServiceImpl.java
  src/main/java/com/security/jwt0Auth/service/test/impl/TestServiceImpl.java
Labels: enhancement

#51 Refactor usability tests.
  src/main/java/com/security/jwt0Auth/service/test/impl/TestServiceImpl.java
Labels: duplicate

#52 Refactor usability tests.
  src/main/java/com/security/jwt0Auth/service/test/impl/TestServiceImpl.java
Labels: duplicate
